// source: Permissions.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

var Nodes_pb = require('./Nodes_pb.js');
goog.object.extend(proto, Nodes_pb);
var Identities_pb = require('./Identities_pb.js');
goog.object.extend(proto, Identities_pb);
goog.exportSymbol('proto.Permission.ActionSet', null, global);
goog.exportSymbol('proto.Permission.ActionSet.NodeOrProviderCase', null, global);
goog.exportSymbol('proto.Permission.Actions', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.Permission.Actions = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.Permission.Actions.repeatedFields_, null);
};
goog.inherits(proto.Permission.Actions, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.Permission.Actions.displayName = 'proto.Permission.Actions';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.Permission.ActionSet = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, proto.Permission.ActionSet.oneofGroups_);
};
goog.inherits(proto.Permission.ActionSet, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.Permission.ActionSet.displayName = 'proto.Permission.ActionSet';
}

/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.Permission.Actions.repeatedFields_ = [1];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.Permission.Actions.prototype.toObject = function(opt_includeInstance) {
  return proto.Permission.Actions.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.Permission.Actions} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.Permission.Actions.toObject = function(includeInstance, msg) {
  var f, obj = {
    actionList: (f = jspb.Message.getRepeatedField(msg, 1)) == null ? undefined : f
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.Permission.Actions}
 */
proto.Permission.Actions.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.Permission.Actions;
  return proto.Permission.Actions.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.Permission.Actions} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.Permission.Actions}
 */
proto.Permission.Actions.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.addAction(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.Permission.Actions.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.Permission.Actions.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.Permission.Actions} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.Permission.Actions.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getActionList();
  if (f.length > 0) {
    writer.writeRepeatedString(
      1,
      f
    );
  }
};


/**
 * repeated string action = 1;
 * @return {!Array<string>}
 */
proto.Permission.Actions.prototype.getActionList = function() {
  return /** @type {!Array<string>} */ (jspb.Message.getRepeatedField(this, 1));
};


/**
 * @param {!Array<string>} value
 * @return {!proto.Permission.Actions} returns this
 */
proto.Permission.Actions.prototype.setActionList = function(value) {
  return jspb.Message.setField(this, 1, value || []);
};


/**
 * @param {string} value
 * @param {number=} opt_index
 * @return {!proto.Permission.Actions} returns this
 */
proto.Permission.Actions.prototype.addAction = function(value, opt_index) {
  return jspb.Message.addToRepeatedField(this, 1, value, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.Permission.Actions} returns this
 */
proto.Permission.Actions.prototype.clearActionList = function() {
  return this.setActionList([]);
};



/**
 * Oneof group definitions for this message. Each group defines the field
 * numbers belonging to that group. When of these fields' value is set, all
 * other fields in the group are cleared. During deserialization, if multiple
 * fields are encountered for a group, only the last value seen will be kept.
 * @private {!Array<!Array<number>>}
 * @const
 */
proto.Permission.ActionSet.oneofGroups_ = [[1,2]];

/**
 * @enum {number}
 */
proto.Permission.ActionSet.NodeOrProviderCase = {
  NODE_OR_PROVIDER_NOT_SET: 0,
  NODE: 1,
  IDENTITY: 2
};

/**
 * @return {proto.Permission.ActionSet.NodeOrProviderCase}
 */
proto.Permission.ActionSet.prototype.getNodeOrProviderCase = function() {
  return /** @type {proto.Permission.ActionSet.NodeOrProviderCase} */(jspb.Message.computeOneofCase(this, proto.Permission.ActionSet.oneofGroups_[0]));
};



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.Permission.ActionSet.prototype.toObject = function(opt_includeInstance) {
  return proto.Permission.ActionSet.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.Permission.ActionSet} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.Permission.ActionSet.toObject = function(includeInstance, msg) {
  var f, obj = {
    node: (f = msg.getNode()) && Nodes_pb.Node.toObject(includeInstance, f),
    identity: (f = msg.getIdentity()) && Identities_pb.Provider.toObject(includeInstance, f),
    action: jspb.Message.getFieldWithDefault(msg, 3, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.Permission.ActionSet}
 */
proto.Permission.ActionSet.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.Permission.ActionSet;
  return proto.Permission.ActionSet.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.Permission.ActionSet} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.Permission.ActionSet}
 */
proto.Permission.ActionSet.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new Nodes_pb.Node;
      reader.readMessage(value,Nodes_pb.Node.deserializeBinaryFromReader);
      msg.setNode(value);
      break;
    case 2:
      var value = new Identities_pb.Provider;
      reader.readMessage(value,Identities_pb.Provider.deserializeBinaryFromReader);
      msg.setIdentity(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setAction(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.Permission.ActionSet.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.Permission.ActionSet.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.Permission.ActionSet} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.Permission.ActionSet.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getNode();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      Nodes_pb.Node.serializeBinaryToWriter
    );
  }
  f = message.getIdentity();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      Identities_pb.Provider.serializeBinaryToWriter
    );
  }
  f = message.getAction();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
};


/**
 * optional Node.Node node = 1;
 * @return {?proto.Node.Node}
 */
proto.Permission.ActionSet.prototype.getNode = function() {
  return /** @type{?proto.Node.Node} */ (
    jspb.Message.getWrapperField(this, Nodes_pb.Node, 1));
};


/**
 * @param {?proto.Node.Node|undefined} value
 * @return {!proto.Permission.ActionSet} returns this
*/
proto.Permission.ActionSet.prototype.setNode = function(value) {
  return jspb.Message.setOneofWrapperField(this, 1, proto.Permission.ActionSet.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.Permission.ActionSet} returns this
 */
proto.Permission.ActionSet.prototype.clearNode = function() {
  return this.setNode(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.Permission.ActionSet.prototype.hasNode = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional Identitiy.Provider identity = 2;
 * @return {?proto.Identitiy.Provider}
 */
proto.Permission.ActionSet.prototype.getIdentity = function() {
  return /** @type{?proto.Identitiy.Provider} */ (
    jspb.Message.getWrapperField(this, Identities_pb.Provider, 2));
};


/**
 * @param {?proto.Identitiy.Provider|undefined} value
 * @return {!proto.Permission.ActionSet} returns this
*/
proto.Permission.ActionSet.prototype.setIdentity = function(value) {
  return jspb.Message.setOneofWrapperField(this, 2, proto.Permission.ActionSet.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.Permission.ActionSet} returns this
 */
proto.Permission.ActionSet.prototype.clearIdentity = function() {
  return this.setIdentity(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.Permission.ActionSet.prototype.hasIdentity = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * optional string action = 3;
 * @return {string}
 */
proto.Permission.ActionSet.prototype.getAction = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/**
 * @param {string} value
 * @return {!proto.Permission.ActionSet} returns this
 */
proto.Permission.ActionSet.prototype.setAction = function(value) {
  return jspb.Message.setProto3StringField(this, 3, value);
};


goog.object.extend(exports, proto.Permission);
